const fs=require('node:fs'),path=require('node:path');const dir=path.join(__dirname,'android');const java=path.join(dir,'app/src/main/java/app/brainboost/mobile');
fs.copyFileSync(path.join(__dirname,'native/MainActivity.java'),path.join(java,'MainActivity.java'));
const manifestPath=path.join(dir,'app/src/main/AndroidManifest.xml');let manifest=fs.readFileSync(manifestPath,'utf8');
if(!manifest.includes('android:name=".MainActivity"')) {
manifest=manifest.replace('<application','<uses-permission android:name="android.permission.INTERNET"/><uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/><application');
manifest=manifest.replace('android:allowBackup="true"','android:allowBackup="false" android:usesCleartextTraffic="false" android:hardwareAccelerated="true"');
manifest=manifest.replace('android:exported="true">\n            <meta-data android:name="android.support.customtabs.trusted.DEFAULT_URL"','android:exported="false" android:configChanges="orientation|screenSize|screenLayout|smallestScreenSize|keyboardHidden|uiMode">\n            <meta-data android:name="android.support.customtabs.trusted.DEFAULT_URL"');
const start=manifest.indexOf('            <intent-filter>\n                <action android:name="android.intent.action.MAIN"');const end=manifest.indexOf('        </activity>',start);const filters=manifest.slice(start,end);manifest=manifest.slice(0,start)+manifest.slice(end);manifest=manifest.replace('<activity android:name="LauncherActivity"',`<activity android:name=".MainActivity" android:exported="true" android:launchMode="singleTask" android:theme="@android:style/Theme.Material.NoActionBar" android:configChanges="orientation|screenSize|screenLayout|smallestScreenSize|keyboardHidden|uiMode|density|layoutDirection" android:windowSoftInputMode="adjustResize">${filters}</activity>\n        <activity android:name="LauncherActivity"`);
}
manifest=manifest.replace('@android:style/Theme.Material.NoActionBar','@style/BrainBoostStartup').replaceAll('@drawable/ic_notification_icon','@drawable/brainboost_notification');fs.writeFileSync(manifestPath,manifest);
fs.mkdirSync(path.join(dir,'app/src/main/res/drawable'),{recursive:true});fs.copyFileSync(path.join(__dirname,'native/brainboost_notification.xml'),path.join(dir,'app/src/main/res/drawable/brainboost_notification.xml'));
fs.copyFileSync(path.join(__dirname,'native/themes.xml'),path.join(dir,'app/src/main/res/values/themes.xml'));
const icon=path.join(dir,'app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml');fs.writeFileSync(icon,fs.readFileSync(icon,'utf8').replace('@android:color/white','@color/backgroundColor'));
const appBuild=path.join(dir,'app/build.gradle');let appGradle=fs.readFileSync(appBuild,'utf8');if(!appGradle.includes("release-signing.gradle"))appGradle+="\napply from: '../../release-signing.gradle'\n";fs.writeFileSync(appBuild,appGradle);
const launcher=path.join(java,'LauncherActivity.java');let activity=fs.readFileSync(launcher,'utf8');if(!activity.includes('Uri requested = getIntent().getData();')) activity=activity.replace('Uri uri = super.getLaunchingUrl();','Uri uri = super.getLaunchingUrl();\n        Uri requested = getIntent().getData();\n        if (requested != null && "https".equals(requested.getScheme()) && "backboost-skill1.vercel.app".equals(requested.getHost())) uri = requested;');fs.writeFileSync(launcher,activity);
const build=path.join(dir,'build.gradle');fs.writeFileSync(build,fs.readFileSync(build,'utf8').replaceAll('jcenter()','mavenCentral()'));
console.log('Applied startup, retry, HTTPS-only navigation, deep links and return/exit handling.');
