const {chromium}=require('playwright');const assert=require('node:assert/strict');
const emails=[process.env.TEST_EMAIL_A,process.env.TEST_EMAIL_B];const password=process.env.TEST_PASSWORD;
if(emails.some(e=>!e)||!password)throw Error('Set disposable TEST_EMAIL_A/B and TEST_PASSWORD');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
const pages=[];for(const email of emails){const context=await browser.newContext();const page=await context.newPage();await page.goto('http://localhost:3000');await page.evaluate(async({email,password})=>{const {supabase}=await import('/src/supabaseClient.js');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;window.testUser={id:data.user.id,email,name:email,skills:[],interests:[],college:'Test',targetRole:'Test'};},{email,password});pages.push(page);}
const ids=await Promise.all(pages.map(p=>p.evaluate(()=>window.testUser.id)));
await pages[0].evaluate(async()=>{const {connectivityService:s}=await import('/src/services/supabaseService.ts');window.stopActivity=s.startActivityTracking();});
await pages[0].waitForFunction(async()=>{const {supabase}=await import('/src/supabaseClient.js');const {data}=await supabase.from('profiles').select('online_status,last_seen_at,online_at').eq('id',window.testUser.id).single();return data?.online_status==='online'&&data.last_seen_at&&data.online_at;});console.log('PASS online heartbeat and activity timestamps');
await pages[0].evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'));});
await pages[0].waitForFunction(async()=>{const {supabase}=await import('/src/supabaseClient.js');const {data}=await supabase.from('profiles').select('online_status').eq('id',window.testUser.id).single();return data?.online_status==='offline';});console.log('PASS offline transition');
await pages[0].evaluate(async()=>{const {connectivityService:s}=await import('/src/services/supabaseService.ts');window.receiptUpdates=0;window.stopReceipt=s.subscribeToRealtimeChat(window.testUser,()=>{},()=>window.receiptUpdates++);});
await pages[0].waitForFunction(async()=>{const {supabase}=await import('/src/supabaseClient.js');return supabase.getChannels().some(c=>c.topic.includes('network-chat-')&&c.state==='joined');});
const sent=await pages[0].evaluate(async receiver=>{const {connectivityService:s,mapRowToNetworkUser}=await import('/src/services/supabaseService.ts');const {supabase}=await import('/src/supabaseClient.js');const {data}=await supabase.from('profiles').select('*').eq('id',receiver).single();return(await s.sendMessage(mapRowToNetworkUser(data),'Receipt test',window.testUser)).newMsg;},ids[1]);assert.equal(sent.isRead,false);assert.ok(!sent.deliveredAt);console.log('PASS saved message starts with single-tick state');
await pages[1].evaluate(async()=>{const {connectivityService:s}=await import('/src/services/supabaseService.ts');await s.fetchConversations(window.testUser);});
await pages[0].waitForFunction(async id=>{const {supabase}=await import('/src/supabaseClient.js');const {data}=await supabase.from('network_messages').select('*').eq('id',id).single();return data?.delivered_at&&!data.is_read;},sent.id);console.log('PASS delivery acknowledgement');
await pages[1].evaluate(async sender=>{const {connectivityService:s}=await import('/src/services/supabaseService.ts');await s.fetchMessagesForUser(sender,window.testUser);},ids[0]);
await pages[0].waitForFunction(async id=>{const {supabase}=await import('/src/supabaseClient.js');const {data}=await supabase.from('network_messages').select('*').eq('id',id).single();return data?.is_read&&data.read_at;},sent.id);await pages[0].waitForFunction(()=>window.receiptUpdates>0);console.log('PASS read receipt and realtime sender update');
const protectedError=await pages[1].evaluate(async id=>{const {supabase}=await import('/src/supabaseClient.js');const {error}=await supabase.from('network_messages').update({content:'Cannot tamper'}).eq('id',id);return !!error;},sent.id);assert.equal(protectedError,true);console.log('PASS receiver cannot edit message content');
const photo=await pages[0].evaluate(async receiver=>{const {connectivityService:s,mapRowToNetworkUser}=await import('/src/services/supabaseService.ts');const {supabase}=await import('/src/supabaseClient.js');const {data}=await supabase.from('profiles').select('*').eq('id',receiver).single();const bytes=Uint8Array.from(atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZYQAAAAASUVORK5CYII='),c=>c.charCodeAt(0));return(await s.sendMessage(mapRowToNetworkUser(data),'Photo privacy test',window.testUser,new File([bytes],'test.png',{type:'image/png'}))).newMsg;},ids[1]);assert.ok(photo.attachmentPath&&photo.attachmentUrl);
const fetched=await pages[1].evaluate(async sender=>{const {connectivityService:s}=await import('/src/services/supabaseService.ts');const msgs=await s.fetchMessagesForUser(sender,window.testUser);const photo=msgs.findLast(m=>m.attachmentPath);return {photo,status:photo?.attachmentUrl?(await fetch(photo.attachmentUrl)).status:0};},ids[0]);assert.equal(fetched.status,200);console.log('PASS private photo renders for receiver and persists in history');
const anonymous=await (await browser.newContext()).newPage();await anonymous.goto('http://localhost:3000');const denied=await anonymous.evaluate(async path=>{const {supabase}=await import('/src/supabaseClient.js');const {error}=await supabase.storage.from('chat-photos').createSignedUrl(path,60);return !!error;},photo.attachmentPath);assert.equal(denied,true);console.log('PASS anonymous user cannot access private photo');
await pages[0].evaluate(async path=>{const {supabase}=await import('/src/supabaseClient.js');await supabase.storage.from('chat-photos').remove([path]);window.stopActivity();window.stopReceipt();},photo.attachmentPath);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
