const fs=require('node:fs'),assert=require('node:assert/strict');const {chromium}=require('playwright');const harness='fresh-chat-check.html';
fs.writeFileSync(harness,`<html><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"><meta name="viewport" content="width=device-width, initial-scale=1"><body><div id="root"></div><script type="module">
import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import '/src/index.css';import {NebulaAIChat} from '/src/components/NebulaAIChat.tsx';import {initialUserProfile} from '/src/data/mockData.ts';import {supabase} from '/src/supabaseClient.js';
const uid='11111111-1111-4111-8111-111111111111',sid='22222222-2222-4222-8222-222222222222';window.messageLoads=0;window.requests=[];window.delayHistory=false;
if(!localStorage.getItem('fixture-seeded')){localStorage.setItem('fixture-seeded','yes');localStorage.setItem('nebula_sessions_'+uid,JSON.stringify([{id:sid,title:'Saved conversation',created_at:new Date().toISOString(),updated_at:new Date().toISOString()}]));localStorage.setItem('nebula_messages_'+sid,JSON.stringify([{id:'old-user',role:'user',content:'Previous question',timestamp:'12:00'},{id:'old-assistant',role:'model',content:'Previous answer',timestamp:'12:01'}]));}
supabase.auth.getSession=async()=>({data:{session:{user:{id:uid}}}});
supabase.from=(table)=>({select(){return this},eq(){return this},order(){return this},limit(){return this},then(resolve){if(table==='ai_chat_messages'){window.messageLoads++;const result={data:null,error:{message:'Fixture uses local saved messages'}};if(window.delayHistory)window.finishHistory=()=>resolve(result);else resolve(result);}else resolve({data:[],error:null});}});
Object.defineProperty(supabase,'functions',{value:{invoke:async(_name,{body})=>{window.requests.push(body);return {data:{sessionId:body.sessionId||'33333333-3333-4333-8333-333333333333',content:'Fresh answer',model:'Fixture'},error:null}}}});
const root=ReactDOM.createRoot(document.getElementById('root'));window.showChat=()=>root.render(React.createElement(NebulaAIChat,{user:{...initialUserProfile,id:uid},onNavigate:()=>{}}));window.hideChat=()=>root.render(null);window.showChat();
</script></body></html>`);
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{for(const width of [390,1440]){const page=await browser.newPage({viewport:{width,height:844}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const welcome=page.getByText('What can I help with today?',{exact:true});const openSidebar=async()=>{const button=page.getByTitle('Open sidebar',{exact:true});if(await button.count())await button.click();};await page.goto('http://localhost:3000/'+harness);await welcome.waitFor();await page.evaluate(()=>document.fonts.ready);await openSidebar();await page.getByText('Saved conversation',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.messageLoads),0);await page.getByText('Saved conversation',{exact:true}).click();await page.getByText('Previous answer',{exact:true}).waitFor();await page.reload();await welcome.waitFor();assert.equal(await page.getByText('Previous answer',{exact:true}).count(),0);assert.equal(await page.evaluate(()=>window.messageLoads),0);await page.getByPlaceholder(/Ask Nebula AI anything/).fill('My fresh question');await page.getByPlaceholder(/Ask Nebula AI anything/).press('Enter');await page.getByText('Fresh answer',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.requests[0].sessionId),null);assert.deepEqual(await page.evaluate(()=>window.requests[0].history),[]);await page.reload();await welcome.waitFor();await page.evaluate(()=>document.fonts.ready);await openSidebar();await page.getByText('My fresh question',{exact:true}).waitFor();await page.getByText('Saved conversation',{exact:true}).click();await page.getByText('Previous answer',{exact:true}).waitFor();await page.evaluate(()=>window.hideChat());await page.waitForFunction(()=>!document.getElementById('root').children.length);await page.evaluate(()=>window.showChat());await welcome.waitFor();assert.equal(await page.getByText('Previous answer',{exact:true}).count(),0);
await openSidebar();await page.evaluate(()=>window.delayHistory=true);await page.getByText('Saved conversation',{exact:true}).click();await page.waitForFunction(()=>!!window.finishHistory);await page.getByTitle('Start New Chat',{exact:true}).click();await page.evaluate(()=>window.finishHistory());await welcome.waitFor();assert.equal(await page.getByText('Previous answer',{exact:true}).count(),0);assert.deepEqual(errors,[]);console.log('PASS refresh/reopen/new-session payload/saved history/stale history at '+width);await page.close();}}finally{await browser.close();fs.unlinkSync(harness)}})().catch(e=>{console.error(e);process.exit(1)});
